url: https://pcdemfoco.github.io
baseurl: ""

# Site settings
title: PcD em Foco
email: romeu.smattos@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Neandro Perini
  pic: neandro
  position: CEO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Neandro
  pic: neandro
  position: COO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Neandro
  pic: neandro
  position: COO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Rua Fulano de Tal
  - line: Forianópolis, SC

# Build settings
markdown: kramdown
permalink: pretty
