url: http://www.pcdemfoco.com.br
baseurl: ""

# Site settings
title: PcD em Foco
email: romeu.smattos@gmail.com
description: "Bem vindo ao maior portal de Santa Catarina exclusivo para pessoas com deficiência que buscam oportunidades adequadas as suas competências e interesses."
image: /img/logo.png

# Team names, titles and social links
people:
- name: Neandro Perini
  pic: neandro
  position: CEO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Neandro
  pic: neandro
  position: COO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Neandro
  pic: neandro
  position: COO, co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: #
  - title: facebook
    url: https://www.facebook.com/PcD-em-Foco-1136871039688188
  # - title: linkedin
  #   url: #

# Postal address (add as many lines as necessary)
address:
  - line: Rua A
  - line: São José, SC

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-seo-tag
